version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3050:3050"
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://localhost:3050