# name: Publish to Docker
# on:
#   push:
#     branches:
#       - main
# permissions:
#   packages: write
#   contents: read
# jobs:
#   publish:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#       # Add your test steps here if needed...
#       - name: Docker meta
#         id: meta
#         uses: docker/metadata-action@v5
#         with:
#           images: ghcr.io/Serhii-Techstarter/publish-packages/game
#           tags: type=sha
#       - name: Login to GHCR
#         uses: docker/login-action@v3
#         with:
#           registry: ghcr.io
#           username: ${{ github.repository_owner }}
#           password: ${{ secrets.GITHUB_TOKEN }}
#       - name: Build container
#         uses: docker/build-push-action@v5
#         with:
#           context: .
#           push: true
#           tags: ${{ steps.meta.outputs.tags }}

# name: Publish Docker Image to GHCR

# on:
#   push:
#     branches:
#       - main

# permissions:
#   contents: read
#   packages: write

# jobs:
#   publish:
#     runs-on: ubuntu-latest
#     steps:
#       # Check out the repository code
#       - name: Checkout Code
#         uses: actions/checkout@v4

#       # Set up Docker metadata for tagging
#       - name: Set up Docker metadata
#         id: meta
#         uses: docker/metadata-action@v5
#         with:
#           images: ghcr.io/serhii-techstarter/to-do-app-scrum-projekt-main/game
#           tags: |
#             type=sha
#             latest

#       # Log in to GitHub Container Registry
#       - name: Login to GitHub Container Registry
#         uses: docker/login-action@v3
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}

#       # Clear Docker cache to avoid conflicts
#       - name: Clear Docker cache
#         run: docker builder prune -af

#       # Build and push the Docker image
#       - name: Build and push Docker image
#         uses: docker/build-push-action@v5
#         with:
#           context: .
#           push: true
#           tags: |
#             ${{ steps.meta.outputs.tags }}


name: Publish Docker Images

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Проверяем код из репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # Логинимся в GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Собираем и публикуем backend-образ
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ghcr.io/serhii-techstarter/to-do-app-backend:latest

      # Собираем и публикуем frontend-образ
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/serhii-techstarter/to-do-app-frontend:latest